kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: docker.1ms.run/library/node:25.3.0
    commands:
      - npm install --registry=https://registry.npmmirror.com
  - name: scp_file
    image: appleboy/drone-scp
    settings:
      host: 172.17.0.1
      username: root
      key:
        from_secret: SSH_PRIVATE_KEY
      source: ./*
      target: /www/wwwroot/service

