kind: pipeline
name: default
type: docker
steps:
  - name: scp_file
    image: appleboy/drone-scp
    settings:
      host: 172.17.0.1
      username: root
      key:
        from_secret: SSH_PRIVATE_KEY
      source: ./*
      target: /www/wwwroot/service